CommonLibraryWeb/Models/BaseRequestModel.cs
namespace CommonLibraryWeb
{
	public class BaseRequestModel
	{
		public int PageIndex { get; set; }
		public int PageSize { get; set; }
	}
}

CommonLibraryWeb/Models/BaseResponseModel.cs
using CommonLibrary;

namespace CommonLibraryWeb
{
	public class BaseResponseModel
	{
		public string Title { get; set; }
		public bool Error { get; set; }
		public string ErrorMsg { get; set; }

		public int PageIndex { get; set; }
		public int PageSize { get; set; }
		public string RedirectUrl { get; set; }
		public ResponseCodes ResponseCode { get; set; }
		public PaginateList PagedListData { get; set; }
	}

	public enum ResponseCodes
	{
		Error = 0,
		Ok = 1,
		NoData = 2,
	}
}

CommonLibraryWeb/Models/MenuItemDto.cs
using CommonLibrary;
using System.Collections.Generic;

namespace CommonLibraryWeb.Models
{
	public class MenuItemDto : BaseDto
	{
		/// <summary>
		/// 显示顺序
		/// </summary>
		public int Order { get; set; }
		/// <summary>
		/// 显示文字
		/// </summary>
		public string MenuText { get; set; }
		/// <summary>
		/// 菜单地址
		/// </summary>
		public string MenuUrl { get; set; }

		public List<MenuItemDto> SubMenus { get; set; }
		public bool HasActiveSubMenu { get; set; }
	}
}

CommonLibraryWeb/Models/MenuResponseModel.cs
using System.Collections.Generic;

namespace CommonLibraryWeb.Models
{
	public class MenuResponseModel : BaseResponseModel
	{
		public MenuResponseModel()
		{
			ResponseCode = ResponseCodes.Ok;
		}
		public List<MenuItemDto> Menus { get; set; }
		public string ActiveMenu { get; set; }
	}
}

CommonLibraryWeb/Controllers/FileUploadController.cs
using CommonLibrary;
using System;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace CommonLibraryWeb.Controllers
{
	public class FileUploadController : BaseController
	{
		private Lazy<IFileUploadHandler> lazyFileUploadHandler;
		protected IFileUploadHandler fileUploadHandler
		{
			get
			{
				return lazyFileUploadHandler.Value;
			}
		}

		public FileUploadController() : base()
		{
			lazyFileUploadHandler = new Lazy<IFileUploadHandler>(() => new FileUploadHandler(), true);
		}

		[ChildActionOnly]
		public PartialViewResult FileUploadPart()
		{
			return PartialView("_FileUploadPart");
		}

		[HttpPost]
		public async Task<JsonResult> ProcessUpload()
		{
			var fileRelativePath = "~/App_Data/UploadFiles" + DateTime.Now.ToString("yyyyMM");
			fileUploadHandler.Init(fileRelativePath, Server.MapPath(fileRelativePath), Session.SessionID);
			var result = await fileUploadHandler.ProcessUpload(Request).ConfigureAwait(false);

			return Json(result);
		}
	}
}

CommonLibraryWeb/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CommonLibraryWeb.Controllers
{
	public class HomeController : Controller
	{
		public ActionResult Index()
		{
			return View();
		}

		public ActionResult About()
		{
			ViewBag.Message = "Your application description page.";

			return View();
		}

		public ActionResult Contact()
		{
			ViewBag.Message = "Your contact page.";

			return View();
		}
	}
}

CommonLibraryWeb/Controllers/LayoutController.cs
using CommonLibraryWeb.Models;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace CommonLibraryWeb.Controllers
{
	public class LayoutController : BaseController
	{
		public ActionResult Error(string errorMsg)
		{
			return View(new BaseResponseModel { ErrorMsg = errorMsg });
		}

		[ChildActionOnly]
		public PartialViewResult SideBarMenu()
		{
			var actMenu = System.Web.HttpContext.Current.Request.RawUrl;
			var responseModel = new MenuResponseModel { Menus = new List<MenuItemDto>(), ActiveMenu = actMenu };
			return PartialView("_SideBarMenu", responseModel);
		}

		private bool FindSubMenu(MenuItemDto m, string url)
		{
			var result = (m?.SubMenus?.Any(x => x.MenuUrl.Equals(url)) == true);

			if (!result && m.SubMenus?.Any() == true)
			{
				foreach (var itm in m.SubMenus)
				{
					result = FindSubMenu(itm, url);
					itm.HasActiveSubMenu = result;
					if (itm.HasActiveSubMenu)
						break;
				}
			}

			return result;
		}

		protected override void Dispose(bool disposing)
		{
			base.Dispose(disposing);
		}
	}
}

CommonLibraryWeb/Controllers/TestPageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CommonLibraryWeb.Controllers
{
    public class TestPageController : Controller
    {
        // GET: TestPage
        public ActionResult Index()
        {
            return View();
        }
    }
}

CommonLibraryWeb/Views/FileUpload/_FileUploadPart.cshtml
<div>
	<button id="btnSelectFile" type="button" class="btn btn-outline-primary">@Html.Translate("selectfile1")</button>
</div>
<div class="form-group" id="selectedfile" name="selectedfile"></div>
<div class="form-group text-danger hidden" id="fileIllegal"></div>
<div class="clearfix"></div>
<script type="text/javascript" language="javascript">
		var utilitiesfileupload = new Utilities();
		var uploaderOpts = { url: '@Url.Action("ProcessUpload","FileUpload", new { Area = "" })' };
		var multiFileUploader = new MultiFileUploader();
		$(function () {
			$('#btnSelectFile').click(function () {
				if ($('#selectedfile .fileitem').length < 6) {
					var $input = $('<input type="file" style="display:none" />');
					$input.appendTo('body');
					$input[0].click();
					$input.change(function(e){
						if (e.target.files && e.target.files.length > 0) {
							var f = e.target.files[0];
							var uploader = new ChunkedUploader(null, uploaderOpts);
							if (f.size > uploader.maximumFileSize) {
								$('#fileIllegal').text('文件大小超过了限制 2M').removeClass('d-none');
							}
							else if (uploader.isFileTypeIllegal(f.name.split('.')[f.name.split('.').length - 1])) {
								$('#fileIllegal').text('非法文件类型').removeClass('d-none');
							}
							else {
								$('#fileIllegal').text('').addClass('d-none');
								var containerId = utilitiesfileupload.generateRandomString(8) + multiFileUploader.chunked_uploaders.length + 1;
								if ($('#' + containerId).length == 0) {
									$('<div class="fileitem input-file-selected" id="' + containerId + '"><span>' + f.name + '</span>&nbsp;' +
	'<span>(' + f.size.formatBytes() + ')</span>&nbsp;' +
	'<button type="button" class="btn btn-outline-info btn-sm uploadfile-doupload">上传文件</button>' +
	'<button type="button" class="btn-close close float-left" aria-label="Close" title="delete"></button></div><div class="clearfix"></div>').appendTo('#selectedfile');
									uploader.setFile(f, containerId);
									multiFileUploader.addFileUploader(uploader);
								}
							}
						}
					});
				}
			});
			$('#selectedfile').delegate("button.close", "click", function (e) {
				multiFileUploader.deleteFile($(this).parent().attr('id'));
			});

			$('#selectedfile').delegate("button.uploadfile-doupload", "click", function (e) {
				multiFileUploader.uploadFile($(this).parent().attr('id'));
			});
		})
</script>

CommonLibraryWeb/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

CommonLibraryWeb/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

CommonLibraryWeb/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

CommonLibraryWeb/Views/Shared/_Layout.cshtml
@model CommonLibraryWeb.BaseResponseModel
<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>@ViewBag.Title</title>
	<link href="~/Content/bootstrap.min.css" rel="stylesheet" />
	<link href="~/Content/common.css" rel="stylesheet" />
	<script src="@Url.Content("~/Scripts/jquery-3.6.0.min.js")"></script>
	<script src="@Url.Content("~/Scripts/popper.min.js")"></script>
	<script src="@Url.Content("~/Scripts/bootstrap.min.js")"></script>
	@*<script src="@Url.Content("~/Scripts/bsmultiselect/dist/js/BsMultiSelect.js")"></script>*@
	@if (Request.IsLocal)
	{
		<script src="@Url.Content("~/Scripts/utility.js?v=1.5")"></script>}
	else
	{
		<script src="@Url.Content("~/Scripts/utility.min.js?v=1.5")"></script>
	}
	@RenderSection("scripts", required: false)
</head>
<body>
	<nav class="navbar navbar-dark bg-main p-0">
		<span class="navbar-brand"><span class="h3">应用</span>名称</span>
		<span class="navbar-nav px-3"><img src="~/Content/img/logo.png" height="40" /></span>
	</nav>
	<nav class="navbar navbar-dark bg-dark p-0">
		<span class="navbar-brand">Welcome,用户名@*@(SessionStateHelper.Get(SessionStateKeys.CurrentLoginUserName)?.ToString())*@</span>
		<span class="navbar-nav px-3"><a class="nav-link" href="@Url.Action("logout", "account")">Logout</a></span>
	</nav>
	<div class="container-fluid">
		<div class="row">
			@Html.Action("SideBarMenu", "Layout")
			<main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-md-4">
				<div class="alert d-none" id="alertMessageContainer" role="alert"></div>
				@RenderBody()
			</main>
		</div>
		<div class="text-center text-muted">Copyright c @DateTime.Now.Year.ToString() company. All Rights Reserved.</div>
	</div>
</body>
</html>

CommonLibraryWeb/Views/Shared/_SideBarMenu.cshtml
@model CommonLibraryWeb.Models.MenuResponseModel
<ul id="menucontainer" class="nav flex-column col-md-3 col-lg-2 d-md-block sidebar collapse">
	@foreach (var itm in Model.Menus)
	{
		<li class="nav-item">
			<a class="pitm menuitem0 @(itm.MenuUrl.Equals(Model.ActiveMenu, StringComparison.OrdinalIgnoreCase) ? "active0" : string.Empty)" href="@itm.MenuUrl">@itm.MenuText</a>
			@if (itm.SubMenus?.Any() == true)
			{
				<ul class="nav flex-column submenucontainer @(itm.HasActiveSubMenu ? "" : "collapse")" style="display:@(itm.HasActiveSubMenu ? "block" : "none")">
					@foreach (var itm2 in itm.SubMenus)
					{
						<li class="nav-item">
							<a class="pitm menuitem1 @(itm2.MenuUrl.Equals(Model.ActiveMenu, StringComparison.OrdinalIgnoreCase) ? "active1" : string.Empty)" href="@itm2.MenuUrl">@itm2.MenuText</a>
							@if (itm2.SubMenus?.Any() == true)
							{
								<ul class="nav flex-column submenucontainer @(itm2.HasActiveSubMenu ? "" : "collapse")" style="display:@(itm2.HasActiveSubMenu ? "block" : "none")">
									@foreach (var itm3 in itm2.SubMenus)
									{
										<li class="nav-item">
											<a class="menuitem2 @(itm3.MenuUrl.Equals(Model.ActiveMenu, StringComparison.OrdinalIgnoreCase) ? "active2" : string.Empty)" href="@itm3.MenuUrl">@itm3.MenuText</a>
										</li>
									}
								</ul>
							}
						</li>
					}
				</ul>
			}
		</li>
	}
</ul>
<script type="text/javascript">
	$(function () {
		$('#menucontainer .pitm').click(function () {
			$(this).next('.submenucontainer').toggle('slow');
		});
	});
</script>

CommonLibraryWeb/Views/TestPage/Index.cshtml
@{
	ViewBag.Title = "Index";
	Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>File upload test</h2>

<form id="fuform" name="fuform" action="#" enctype="application/x-www-form-urlencoded">
	<div class="form-group">
		<label for="cpUploadTestfiletoupload">@Html.Translate("lab_uploadattach")</label>
		<span class="text-warning">@Html.Translate("lab_fileuploadtips")</span>
		@*<div>
			<button id="btnSelectFile_cpUploadTest" type="button" class="btn btn-primary">@Html.Translate("lab_selectfile1")</button>
		</div>
		<div class="form-group" id="cpuploadtestselectedfile" name="cpuploadtestselectedfile"></div>
		<div class="form-group text-danger hidden" id="cpUploadTestfileIllegal"></div>
		<div class="clearfix"></div>*@
		@Html.Action("FileUploadPart", "FileUpload")
	</div>
</form>
@section scripts{
	@if (Request.IsLocal)
	{
		<script src="@Url.Content("~/Scripts/uploader.js?v=1.5")"></script>}
	else
	{
		<script src="@Url.Content("~/Scripts/uploader.min.js?v=1.5")"></script>
	}
<script language="javascript" type="text/javascript">
	@*var utilities8 = new Utilities({ msgBoxId: '#alertMessageContainer', secconds: 2 });
	var cpUploadTestUploaderOpts = { url: '@Url.Action("ProcessUpload","FileUpload", new { Area = "" })', errMsgContainer: "#cpUploadTestfileIllegal" };
	var multiFileUploader_cpUploadTest = new MultiFileUploader();
	$(function () {
		$('#btnSelectFile_cpUploadTest').click(function () {
			if ($('#cpuploadtestselectedfile .fileitem').length < 6) {
				var $input = $('<input type="file" style="display:none" />').appendTo('body');
					$input.trigger('click');
					$input.change(function(e){
						if (e.target.files && e.target.files.length > 0) {
							var f = e.target.files[0];
							var uploader = new ChunkedUploader(null, cpUploadTestUploaderOpts);
							if (f.size > uploader.maximumFileSize) {
								$('#cpUploadTestfileIllegal').text('400MB @Html.Translate("msg_maximumforuploadfilesize")').removeClass('hidden');
							}
							else if (uploader.isFileTypeIllegal(f.name.split('.')[f.name.split('.').length - 1])) {
								$('#cpUploadTestfileIllegal').text('@Html.Translate("msg_filetypeillegal")').removeClass('hidden');
							}
							else {
								$('#cpUploadTestfileIllegal').addClass('hidden');
								var containerId = utilities8.generateRandomString(8) + multiFileUploader_cpUploadTest.chunked_uploaders.length + 1;
								if ($('#' + containerId).length == 0) {
									$('<div class="fileitem input-file-selected" id="' + containerId + '"><span>' + f.name + '</span>&nbsp;' +
	'<span>(' + f.size.formatBytes() + ')</span>&nbsp;' +
	'<button type="button" class="btn btn btn-info btn-sm uploadfile-doupload text-white">@Html.Translate("lab_upload_files")</button>' +
	'<button type="button" class="btn-close close" aria-label="Close" title="@Html.Translate("pub_del")"></button></div><div class="clearfix"></div>').appendTo('#cpuploadtestselectedfile');
									uploader.setFile(f, containerId);
									multiFileUploader_cpUploadTest.addFileUploader(uploader);
								}
							}
						}
					});
			}
		});
		$('#cpuploadtestselectedfile').delegate("button.close", "click", function (e) {
			multiFileUploader_cpUploadTest.deleteFile($(this).parent().attr('id'));
		});
		$('#cpuploadtestselectedfile').delegate("button.uploadfile-doupload", "click", function (e) {
			multiFileUploader_cpUploadTest.uploadFile($(this).parent().attr('id'));
		});
	});*@

</script>
}